import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";

const futura = localFont({
  src: "../../public/fonts/futura/futur.ttf",
  variable: "--font-futura",
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Irchad",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${futura.variable} ${montserrat.variable} antialiased font-montserrat`}>
        {children}
      </body>
    </html>
  );
}
