import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import Sidebar from "@/components/layout/sidebar";
import Header from "@/components/layout/header";

const futura = localFont({
  src: "../../public/fonts/futura/futur.ttf",
  variable: "--font-futura",
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

//user role is specified here for testing purposes
const userRole = "admin";

export const metadata: Metadata = {
  title: "Irchad",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${futura.variable} ${montserrat.variable} antialiased font-montserrat bg-white`}>
        <div className="flex min-h-screen">{children}</div>
      </body>
    </html>
  );
}
